version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.3.1
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers
    executor: aws-cli/default
    steps:
      - checkout
      - restore_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run: xvfb-run -a npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      - run: xvfb-run -a npm run deploy-aws